### ISSUE TITLE
goroutine error with default run

### ISSUE THREAD

**Issue by ehsandeep** [mhmdiaa/second-order#1] opened 2017-07-20 15:09 UTC
lots of error popped while running using default option after couple of second of crawling.

````
goroutine 7108 [runnable]:
net/http.(*http2clientStream).awaitRequestCancel(0xc448ab1e00, 0xc436c47e00)
        /usr/local/go/src/net/http/h2_bundle.go:5588
created by net/http.(*http2clientConnReadLoop).handleResponse
        /usr/local/go/src/net/http/h2_bundle.go:6822 +0x6f7
exit status 2
````

**Comment by mhmdiaa** [comment] 2017-07-20 17:28
Can you give me the target you ran it on? Also, try running it with `-depth=1`, and let me know what happens.

**Comment by ehsandeep** [comment] 2017-07-20 17:39
i used https://hackerone.com, anyway i ran the same now but didnt encountered the error. what is it mean?

and if using `-depth=1` just input url returns back.

**Comment by mhmdiaa** [comment] 2017-07-20 18:03
It seems like an issue with concurrency. I'll look into it.
When you ran it the second time, was the output written normally to `/output`?

**Comment by ehsandeep** [comment] 2017-07-20 18:41
last time when i ran, i did without output option, so not sure about that, and now i am trying same with/without output option getting that error continuously, so can't say about that.

**Comment by mhmdiaa** [comment] 2017-07-20 20:03
Actually, the output is automatically written, the flag only specifies the name of the directory where it will be stored.
Anyway, I'm sure this has to do with the part of the code that handles concurrency, it's a little messy. I'm going to rewrite it, so your problem should be resolved with the next update.

**Comment by ehsandeep** [comment] 2017-07-20 20:19
Okay, Thanks 👍

**Comment by mhmdiaa** [comment] 2017-07-21 22:28
I made some changes that might solve your problem, or at least tell us more about the cause of it. Can you pull the changes to your local repo and try again?
I just ran it on https://hackerone.com and it works fine. Here is the command I used:
```
go run second-order.go -base=https://hackerone.com -depth=2 -js
```
By the way, I think the error message you pasted above is missing a line (the first line exactly).

**Comment by ehsandeep** [comment] 2017-07-22 01:35
Hey @mhmdiaa sorry for that & thanks for update and making it!

````
fatal error: concurrent map writes

goroutine 432 [running]:
runtime.throw(0x6d5ec1, 0x15)
        /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc427379c00 sp=0xc427379be0
runtime.mapassign(0x67ed40, 0xc420016f00, 0xc427379fb8, 0xc435bb2060)
        /usr/local/go/src/runtime/hashmap.go:499 +0x667 fp=0xc427379ca0 sp=0xc427379c00
main.crawl(0xc420203340, 0x35, 0x1, 0xc42008a240, 0xc420014fa0)
        /root/second-order/second-order.go:85 +0x970 fp=0xc427379fb8 sp=0xc427379ca0
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc427379fc0 sp=0xc427379fb8
created by main.dedup
        /root/second-order/second-order.go:43 +0x228

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc420014fac)
        /usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc420014fa0)
        /usr/local/go/src/sync/waitgroup.go:131 +0x7a
main.main()
        /root/second-order/second-order.go:235 +0x13c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 4 [chan receive]:
main.dedup(0xc42008a240, 0xc420014fa0)
        /root/second-order/second-order.go:37 +0x105
created by main.main
        /root/second-order/second-order.go:233 +0xb0

goroutine 28 [IO wait]:
net.runtime_pollWait(0x7ff2523e5f58, 0x72, 0x3)
        /usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420164688, 0x72, 0x7fb1c0, 0x7f8428)
        /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420164688, 0xc421738000, 0x8000)
        /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc420164620, 0xc421738000, 0x8000, 0x8000, 0x0, 0x7fb1c0, 0x7f8428)
        /usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42000e028, 0xc421738000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:181 +0x70
crypto/tls.(*block).readFromUntil(0xc420208a50, 0x7ff252361000, 0xc42000e028, 0x5, 0xc42000e028, 0x0)
````

i ran for 2-3 times it works perfectly but when i increased `depth=5` i got this error, and from error i dont think its problem in code, it's something related to Go concurrency issue.

**Comment by ehsandeep** [comment] 2017-07-22 01:38
something similar to: https://github.com/golang/dep/issues/136

i also noticed this error is not persistence, sometime it occurs and sometime it works!

**Comment by mhmdiaa** [comment] 2017-07-22 18:26
I've pushed some changes that may solve this problem. Can you check if it works now?

**Comment by ehsandeep** [comment] 2017-07-22 18:52
Yes @mhmdiaa, i guess the last error got fixed, and worked well for the 1st time, while running again just for testing, i see this:

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x6d6a72, 0x16)
        /usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sysMap(0xc7a8b70000, 0x100000, 0x7f8b57ff6c00, 0x8474b8)
        /usr/local/go/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x82e9a0, 0x100000, 0x7f8b494df3a8)
        /usr/local/go/src/runtime/malloc.go:440 +0x374
runtime.(*mheap).grow(0x82e9a0, 0x4, 0x0)
        /usr/local/go/src/runtime/mheap.go:774 +0x62
runtime.(*mheap).allocSpanLocked(0x82e9a0, 0x4, 0xc421417000)
        /usr/local/go/src/runtime/mheap.go:678 +0x44f
runtime.(*mheap).alloc_m(0x82e9a0, 0x4, 0x42, 0xc42001eb28)
        /usr/local/go/src/runtime/mheap.go:562 +0xe2
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:627 +0x4b
runtime.systemstack(0x7f8b57ff6d58)
        /usr/local/go/src/runtime/asm_amd64.s:343 +0xab
runtime.(*mheap).alloc(0x82e9a0, 0x4, 0x10000000042, 0x4111bd)
        /usr/local/go/src/runtime/mheap.go:628 +0xa0
runtime.(*mcentral).grow(0x8319b0, 0x0)
        /usr/local/go/src/runtime/mcentral.go:212 +0x8e
runtime.(*mcentral).cacheSpan(0x8319b0, 0xc42001eb28)
        /usr/local/go/src/runtime/mcentral.go:93 +0x12a
runtime.(*mcache).refill(0x7f8b81629e10, 0xc700000042, 0x0)
        /usr/local/go/src/runtime/mcache.go:122 +0xa0
runtime.(*mcache).nextFree.func1()
        /usr/local/go/src/runtime/malloc.go:538 +0x32
runtime.systemstack(0xc42001c600)
        /usr/local/go/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1132

goroutine 211039 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:281 fp=0xc779779128 sp=0xc779779120
runtime.(*mcache).nextFree(0x7f8b81629e10, 0xc421417042, 0x44fe90, 0xc421417000, 0x0)
        /usr/local/go/src/runtime/malloc.go:539 +0xb9 fp=0xc779779180 sp=0xc779779128
runtime.mallocgc(0x8000, 0x66b320, 0x411301, 0xc7a8b25688)
        /usr/local/go/src/runtime/malloc.go:691 +0x827 fp=0xc779779220 sp=0xc779779180
runtime.makeslice(0x66b320, 0x8000, 0x8000, 0x7fc700, 0xc7a896b200, 0x201)
        /usr/local/go/src/runtime/slice.go:54 +0x7b fp=0xc779779270 sp=0xc779779220
compress/flate.NewReader(0x7fa800, 0xc7a896b200, 0xc7a896b200, 0x7fa800)
        /usr/local/go/src/compress/flate/inflate.go:792 +0x28b fp=0xc779779348 sp=0xc779779270
compress/gzip.(*Reader).readHeader(0xc7a8a41b80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/compress/gzip/gunzip.go:238 +0x309 fp=0xc779779400 sp=0xc779779348
compress/gzip.(*Reader).Reset(0xc7a8a41b80, 0x7f8b7ce4c828, 0xc7a4809cc0, 0x697880, 0x200)
        /usr/local/go/src/compress/gzip/gunzip.go:113 +0x12e fp=0xc7797797e0 sp=0xc779779400
compress/gzip.NewReader(0x7f8b7ce4c828, 0xc7a4809cc0, 0xc7a4809cc0, 0x7f8b7ce4c828, 0xc7a4809cc0)
        /usr/local/go/src/compress/gzip/gunzip.go:94 +0x58 fp=0xc779779820 sp=0xc7797797e0
net/http.(*http2gzipReader).Read(0xc7a70c9f20, 0xc7a8a3aa00, 0x200, 0x200, 0x428a6e, 0xc42089a5d8, 0x6e2408)
        /usr/local/go/src/net/http/h2_bundle.go:7286 +0xd2 fp=0xc779779878 sp=0xc779779820
bytes.(*Buffer).ReadFrom(0xc779779918, 0x7f8b7ce4c800, 0xc7a70c9f20, 0xc7a8a3aa00, 0x0, 0x200)
        /usr/local/go/src/bytes/buffer.go:179 +0x160 fp=0xc7797798e8 sp=0xc779779878
io/ioutil.readAll(0x7f8b7ce4c800, 0xc7a70c9f20, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:33 +0x150 fp=0xc779779990 sp=0xc7797798e8
io/ioutil.ReadAll(0x7f8b7ce4c800, 0xc7a70c9f20, 0xc7a70c9f20, 0x7f8b7ce4c800, 0xc7a70c9f20, 0x27, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:42 +0x3e fp=0xc7797799e0 sp=0xc779779990
main.getScript(0xc7a49efcb0, 0x27, 0xc49825d940, 0x3d, 0x0, 0x0, 0x0, 0x0)
        /root/second-order/second-order.go:170 +0x3b5 fp=0xc779779ad8 sp=0xc7797799e0
main.scrapeScripts.func1(0x0, 0xc7a49efaa0)
        /root/second-order/second-order.go:145 +0xc2 fp=0xc779779bc8 sp=0xc779779ad8
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc7a49efa70, 0xc779779c68, 0x6)
        /root/go/src/github.com/PuerkitoBio/goquery/iteration.go:10 +0x113 fp=0xc779779c20 sp=0xc779779bc8
main.scrapeScripts(0xc7a47f73e0, 0xc49825d940, 0x3d, 0x0, 0x0, 0x0, 0x0)
        /root/second-order/second-order.go:153 +0x119 fp=0xc779779ca0 sp=0xc779779c20
main.crawl(0xc49825d940, 0x3d, 0x1, 0xc4200702a0, 0xc420014fa0)
        /root/second-order/second-order.go:94 +0x936 fp=0xc779779fb8 sp=0xc779779ca0
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc779779fc0 sp=0xc779779fb8
created by main.dedup
        /root/second-order/second-order.go:54 +0x228

goroutine 1 [semacquire, 1 minutes]:
sync.runtime_Semacquire(0xc420014fac)
````
and this seems to lack of memory on the machine i guess ?

**Comment by mhmdiaa** [comment] 2017-07-22 20:07
There was an issue with how I close response bodies after issuing a request, this lead to a massive portion of the memory being allocated and never freed. This is fixed now. Can you try it?
Thank you for your time.

**Comment by ehsandeep** [comment] 2017-07-22 20:23
Hey @mhmdiaa,

i still see the same after 2nd run:

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x6d6a72, 0x16)
        /usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sysMap(0xc7c7e10000, 0x100000, 0x7f8ec8ca8c00, 0x8474b8)
        /usr/local/go/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x82e9a0, 0x100000, 0x7f8e9b5670a8)
        /usr/local/go/src/runtime/malloc.go:440 +0x374
runtime.(*mheap).grow(0x82e9a0, 0x4, 0x0)
        /usr/local/go/src/runtime/mheap.go:774 +0x62
runtime.(*mheap).allocSpanLocked(0x82e9a0, 0x4, 0x7f8ec8ca8ce8)
        /usr/local/go/src/runtime/mheap.go:678 +0x44f
runtime.(*mheap).alloc_m(0x82e9a0, 0x4, 0x42, 0x7f8e9b567058)
        /usr/local/go/src/runtime/mheap.go:562 +0xe2
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:627 +0x4b
runtime.systemstack(0x7f8ec8ca8d58)
        /usr/local/go/src/runtime/asm_amd64.s:343 +0xab
runtime.(*mheap).alloc(0x82e9a0, 0x4, 0x10000000042, 0x7f8e9b567010)
        /usr/local/go/src/runtime/mheap.go:628 +0xa0
runtime.(*mcentral).grow(0x8319b0, 0x0)
        /usr/local/go/src/runtime/mcentral.go:212 +0x8e
runtime.(*mcentral).cacheSpan(0x8319b0, 0xc42001e528)
        /usr/local/go/src/runtime/mcentral.go:93 +0x12a
runtime.(*mcache).refill(0x7f8ecbda64b0, 0xc700000042, 0xc7c7df9800)
        /usr/local/go/src/runtime/mcache.go:122 +0xa0
runtime.(*mcache).nextFree.func1()
        /usr/local/go/src/runtime/malloc.go:538 +0x32
runtime.systemstack(0xc42005e6c0)
        /usr/local/go/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1132

goroutine 9356 [running]:
runtime.systemstack_switch()
````

**Comment by mhmdiaa** [comment] 2017-07-22 20:41
Is this the whole error? If it's not, please send the whole error. It may appear to be the same, but there might be some slight differences (like function names).
Would you mind telling me how much memory your machine has?
Can you create a swap file on your machine and tell me what happens?

**Comment by ehsandeep** [comment] 2017-07-22 21:12
Hey @mhmdiaa,

i have 8GM memory in remote machine.

and i ran 4-5 times, but didnt seen the error, may be using aggressively will cause that issue.
anyway do you mind to share the info about `resources.json`, idk what it suppose to save, but its blank for all scans, and only i can see the JS files getting saved, where the URI endpoints getting saved?

**Comment by mhmdiaa** [comment] 2017-07-22 21:41
Unlikely, because all allocated memory is supposed to be freed after the program finishes. I can't be sure without the complete error which you didn't send.
`resources.json` contains the URLs of several third-party providers that are embedded in any page (in an `iframe` tag's `src` for example). It currently identifies S3 and Wufoo only. If you want it to identify more, edit the `providers` slice at line 223.
If this file is empty, the site you crawled doesn't use either of these services. See the blog at the end of the README for more info.

**Comment by ehsandeep** [comment] 2017-07-22 21:55
Okay i will provide full error, as soon as i see them, anyway isn't it's good to save the requested url/endpoints as well into file? eg:

````
https://test.com/test132
https://test.com/macc/23
````

**Comment by mhmdiaa** [comment] 2017-07-22 22:14
Thank you. That's an interesting idea. Feel free to open a new issue with more details.
Let me know about any problem/feature/improvement you have in mind.

**Comment by ehsandeep** [comment] 2017-07-22 22:17
Sure.

**Comment by ehsandeep** [comment] 2017-07-25 09:17
@mhmdiaa here is the complete error if it helps!

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x6d6a72, 0x16)
        /usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sysMap(0xc7c20f0000, 0xcc300000, 0x456600, 0x8474b8)
        /usr/local/go/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x82e9a0, 0xcc300000, 0x7ffbafe6ece0)
        /usr/local/go/src/runtime/malloc.go:440 +0x374
runtime.(*mheap).grow(0x82e9a0, 0x6617e, 0x0)
        /usr/local/go/src/runtime/mheap.go:774 +0x62
runtime.(*mheap).allocSpanLocked(0x82e9a0, 0x6617e, 0x7ffbaffa3718)
        /usr/local/go/src/runtime/mheap.go:678 +0x44f
runtime.(*mheap).alloc_m(0x82e9a0, 0x6617e, 0x100000000, 0xffffffffffffffff)
        /usr/local/go/src/runtime/mheap.go:562 +0xe2
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:627 +0x4b
runtime.systemstack(0x7ffbafe6edd8)
        /usr/local/go/src/runtime/asm_amd64.s:343 +0xab
runtime.(*mheap).alloc(0x82e9a0, 0x6617e, 0x10100000000, 0x0)
        /usr/local/go/src/runtime/mheap.go:628 +0xa0
runtime.largeAlloc(0xcc2faaab, 0x7ffbd3d37401, 0xc400000004)
        /usr/local/go/src/runtime/malloc.go:807 +0x93
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:702 +0x3e
runtime.systemstack(0xc42001f900)
        /usr/local/go/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1132

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:281 fp=0xc42047e738 sp=0xc42047e730
runtime.mallocgc(0xcc2faaab, 0x66b320, 0xc494f31201, 0xc4f265eae0)
        /usr/local/go/src/runtime/malloc.go:703 +0x930 fp=0xc42047e7d8 sp=0xc42047e738
runtime.makeslice(0x66b320, 0xcc2faaab, 0xcc2faaab, 0xc42047e878, 0x41131c, 0xc44dcc19a0)
        /usr/local/go/src/runtime/slice.go:54 +0x7b fp=0xc42047e828 sp=0xc42047e7d8
bytes.makeSlice(0xcc2faaab, 0x0, 0x0, 0x0)
        /usr/local/go/src/bytes/buffer.go:201 +0x77 fp=0xc42047e868 sp=0xc42047e828
bytes.(*Buffer).grow(0xc4307520b0, 0x99, 0x1)
        /usr/local/go/src/bytes/buffer.go:109 +0x177 fp=0xc42047e8b8 sp=0xc42047e868
bytes.(*Buffer).WriteString(0xc4307520b0, 0xc52b42f16c, 0x99, 0x0, 0x0, 0x0)
        /usr/local/go/src/bytes/buffer.go:146 +0x41 fp=0xc42047e8e8 sp=0xc42047e8b8
encoding/json.(*encodeState).string(0xc4307520b0, 0xc52b42c000, 0x7577, 0xc52b42c001, 0x7577)
        /usr/local/go/src/encoding/json/encode.go:893 +0x11a fp=0xc42047e960 sp=0xc42047e8e8
encoding/json.stringEncoder(0xc4307520b0, 0x66b160, 0xc527e532b0, 0x98, 0xc527e50100)
        /usr/local/go/src/encoding/json/encode.go:608 +0x214 fp=0xc42047ea20 sp=0xc42047e960
encoding/json.(*mapEncoder).encode(0xc5d4c1e038, 0xc4307520b0, 0x67f1a0, 0xc524664750, 0x15, 0x66170100)
        /usr/local/go/src/encoding/json/encode.go:690 +0x589 fp=0xc42047eb90 sp=0xc42047ea20
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc4307520b0, 0x67f1a0, 0xc524664750, 0x15, 0xc509350100)
        /usr/local/go/src/encoding/json/encode.go:706 +0x64 fp=0xc42047ebd0 sp=0xc42047eb90
encoding/json.(*mapEncoder).encode(0xc5d4c1e040, 0xc4307520b0, 0x67f080, 0xc420078f00, 0x15, 0x670100)
        /usr/local/go/src/encoding/json/encode.go:690 +0x589 fp=0xc42047ed40 sp=0xc42047ebd0
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc4307520b0, 0x67f080, 0xc420078f00, 0x15, 0xc420070100)
        /usr/local/go/src/encoding/json/encode.go:706 +0x64 fp=0xc42047ed80 sp=0xc42047ed40
encoding/json.(*encodeState).reflectValue(0xc4307520b0, 0x67f080, 0xc420078f00, 0x15, 0x100)
        /usr/local/go/src/encoding/json/encode.go:323 +0x82 fp=0xc42047edb8 sp=0xc42047ed80
encoding/json.(*encodeState).marshal(0xc4307520b0, 0x67f080, 0xc420078f00, 0xc420040100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:296 +0xb8 fp=0xc42047edf0 sp=0xc42047edb8
encoding/json.Marshal(0x67f080, 0xc420078f00, 0xc6b2fca000, 0x3c0146ca, 0x75e96c81, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:161 +0x6e fp=0xc42047ee38 sp=0xc42047edf0
main.main()
        /root/second-order/second-order.go:257 +0x1cf fp=0xc42047ef88 sp=0xc42047ee38
runtime.main()
        /usr/local/go/src/runtime/proc.go:185 +0x20a fp=0xc42047efe0 sp=0xc42047ef88
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42047efe8 sp=0xc42047efe0

goroutine 17 [syscall, 8 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 19 [chan receive, 5 minutes]:
main.dedup(0xc420070300, 0xc420072ef0)
        /root/second-order/second-order.go:48 +0x105
created by main.main
        /root/second-order/second-order.go:251 +0xb0
exit status 2
```

**Comment by mhmdiaa** [comment] 2017-07-25 13:07
Thank you! It helps so much. This error has a completely different cause. I'll reopen this issue, and fix it shortly.

**Comment by mhmdiaa** [comment] 2017-07-28 14:55
This error was raised when the tool was attempting to marshal a gigantic JSON object that contained external JS files' contents. The best kind of fix is when you remove the problematic function altogether. Second Order now doesn't fetch external scripts; it just logs their URLs, you can then use these URLs to fetch the code. Can you verify this fixes your problem?

**Closed as completed** 2017-07-29 21:38 UTC
